Team-UACC/connectable-backend

src/main/java/com/backend/connectable/user/domain/User.java, src/main/java/com/backend/connectable/user/service/UserService.java, src/test/java/com/backend/connectable/user/domain/UserTest.java, src/test/java/com/backend/connectable/user/service/UserServiceTest.java
- Klip 로그인만을 수행한 유저에 대해서는 (전화번호/닉네임 미등록) isNew=true 를 반환하도록 수정
=> fix: Klip 로그인만 수행한 유저에 대해 isNew 값 상이하게 지정

src/main/java/com/backend/connectable/user/ui/dto/UserResponse.java, src/test/java/com/backend/connectable/user/service/UserServiceTest.java
- 유저 상세 조회시 ResponseBody에 status=success 필드 추가
- 조회 실패시 추후 예외처리를 고려하여, 성공 케이스로 하드코딩 되어있음
=> fix: 유저 상세 조회시 status 추가

src/main/java/com/backend/connectable/user/domain/repository/UserRepositoryCustom.java, src/main/java/com/backend/connectable/user/domain/repository/UserRepositoryImpl.java, src/main/java/com/backend/connectable/user/service/UserService.java, src/test/java/com/backend/connectable/user/service/UserServiceTest.java
- 영속성 컨텍스트로 관리하던 user 변경기능 query 로 처리하도록 변경
- Security와 Transaction 간의 연관이 있는지 확인 후 분리하기
=> feat: 유저 수정 기능 queryDsl로 변경

src/main/java/com/backend/connectable/DataLoader.java, src/main/java/com/backend/connectable/artist/domain/Artist.java, src/main/java/com/backend/connectable/artist/domain/repository/ArtistRepository.java, src/main/java/com/backend/connectable/event/domain/Event.java, src/main/java/com/backend/connectable/event/domain/Ticket.java, src/main/java/com/backend/connectable/event/domain/dto/EventTicket.java, src/main/java/com/backend/connectable/event/domain/dto/EventTickets.java, src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryCustom.java, src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryImpl.java, src/main/java/com/backend/connectable/event/service/EventService.java, src/main/java/com/backend/connectable/event/ui/EventController.java, src/main/java/com/backend/connectable/event/ui/dto/TicketResponse.java, src/test/java/com/backend/connectable/event/domain/repository/TicketRepositoryTest.java, src/test/java/com/backend/connectable/event/service/EventServiceTest.java, src/test/java/com/backend/connectable/event/ui/EventControllerTest.java
- 이벤트에 귀속된 티켓 목록 조회 api
- 특정 티켓 상세 조회 api
+) Get 메소드로 조회하는 경우 비즈니스 로직이 들어가있지 않아 통합테스트로 충분하다 판단하였습니다. 
+) 경로는 [링크](https://blog.restcase.com/7-rules-for-rest-api-uri-design/) 에 따라 camelCase가 아닌 hyphen을 사용하였습니다. 
- 데이터의 nullable 조건에 따라 논리적 Join 검토 필요
- TicketMetadata가 null로 내려오는 현상 fix 필요 
ㄴ [@QueryType](http://querydsl.com/static/querydsl/5.0.0/reference/html_single/)로 타입을 강제할 수 있지않을까 하였으나, DB에 Text 타입과 String 타입을 매핑했음에도 값이 null로 내려옵니다.
ㄴ [Reference](https://github.com/querydsl/querydsl/issues/2652)
=> feat: 이벤트 조회 api

src/main/java/com/backend/connectable/event/domain/dto/EventTicket.java, src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryImpl.java, src/main/java/com/backend/connectable/user/domain/dto/UserTicket.java, src/main/java/com/backend/connectable/user/domain/repository/UserRepositoryImpl.java, src/main/java/com/backend/connectable/user/ui/dto/UserTicketResponse.java
- 일부 쿼리 QueryProjection 적용
ㄴ 필드가 많은 쿼리의 경우는 순서 잘못 기입되는 이슈를 우려하여, bean 프로젝션으로 남겨두었습니다. 
- 인덴트 잘못된 부분 수정
- User metadata fix
- Service 레이어에서 DTO trans 하는 부분 DTO 로 끌고 들어가는 부분에 대해서는 수요일까지 조금 더 고민해보겠습니다 :)
=> refactor: 티켓 도메인 쿼리 인덴트 수정 및 QueryProjection 적용, User metadata fix

src/main/java/com/backend/connectable/event/ui/dto/TicketMetadataAttributeResponse.java, src/main/java/com/backend/connectable/event/ui/dto/TicketMetadataResponse.java, src/main/java/com/backend/connectable/event/ui/dto/TicketResponse.java, src/test/java/com/backend/connectable/event/ui/EventControllerTest.java
- domain을 보호하기 위해 티켓 메타데이터에 dto를 도입합니다.
=> fix: 티켓 메타데이터 dto 도입

build.gradle, src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryImpl.java, src/main/java/com/backend/connectable/event/mapper/EventMapper.java, src/main/java/com/backend/connectable/event/service/EventService.java, src/main/java/com/backend/connectable/event/ui/EventController.java, src/main/java/com/backend/connectable/event/ui/dto/EventDetailResponse.java, src/test/java/com/backend/connectable/event/ui/EventControllerTest.java
- service 레이어 내 DTO 주입하는 부분 Mapper 로 변경 ( [참고 링크](https://www.baeldung.com/mapstruct) )
ㄴ변경 사유 
1. 많은 수의 필드를 빌더 패턴으로 주입하여 가독성 저해
2.  필드 네이밍 오기입 확률 떨어짐 
3. 컴파일 통과시, Mapper 구현체를 통해 디버깅 가능
- 규격화를 위해 응답 컨트롤러 ResponseEntity Wrapping
- lombok 하위에 mapstruct 의존성 위치해야 함. 
- date 필드 startTime과 동일하여 제거
- 테스트 코드 강화 필요
=> refactor: service 레이어 Mapper 사용하여 DTO 변환 및 컨트롤러 ResponseEntity 변경

src/main/java/com/backend/connectable/event/service/EventService.java
- GET /events/{event-id}/tickets/{ticket-id} 조회 시 ticketSalesStatus Null 로 내려오는 현상 수정
=> fix: ticketSalesStatus null 로 내려오는 현상 수정

src/main/java/com/backend/connectable/ConnectableApplication.java, src/main/java/com/backend/connectable/global/entity/BaseEntity.java, src/main/java/com/backend/connectable/order/domain/Order.java, src/main/java/com/backend/connectable/order/domain/OrderDetail.java, src/main/java/com/backend/connectable/order/domain/OrderStatus.java, src/main/java/com/backend/connectable/order/domain/repository/OrderDetailRepository.java, src/main/java/com/backend/connectable/order/domain/repository/OrderRepository.java, src/main/java/com/backend/connectable/order/service/OrderService.java, src/main/java/com/backend/connectable/order/ui/OrderController.java, src/main/java/com/backend/connectable/order/ui/dto/OrderRequest.java, src/main/java/com/backend/connectable/order/ui/dto/OrderResponse.java, src/main/java/com/backend/connectable/security/SecurityConfiguration.java, src/test/java/com/backend/connectable/event/ui/EventControllerTest.java, src/test/java/com/backend/connectable/order/service/OrderServiceTest.java
- 주문등록시 주문 및 주문상세 정보 등록 API 추가
ㄴ 주문 서비스 레이어쪽이 OrderDetail과 Order를 들고 있는데, 이를 분리할 방법에 대해 고안이 필요합니다. 
[링크](https://techblog.woowahan.com/2668/) 에서 Embed를 활용하는 방법은 원테이블이 될 것 같아, 우선 엔티티 분리되는 방향으로 작성하였습니다. Best-practice가 있다면 공유해주시면 감사하겠습니다. 
- SecurityConfiguration에 orders 엔드포인트 추가
- WebMVCTest시 JPA Bean 을 등록하지 않아 @MockBean(JpaMetamodelMappingContext.class) 추가
- 예약어 이슈로 Order 엔티티 orders로 테이블 명명
- 트랜잭션 방법 정한 뒤, OrderService Layer 예외처리 필요
- Slack appender는 별도 브랜치 작성 예정
=> feat: 주문 등록 기능 API 추가

src/main/java/com/backend/connectable/event/domain/TicketMetadata.java, src/main/java/com/backend/connectable/event/domain/TicketMetadataAttribute.java
1. **TicketMetadata 필드에 대해 hibernate가 dirty check를 제대로 하지 못하는 문제를 발견하여, 해당 도메인 필드에 대해서 hashcode/equals를 재정의하였습니다.**
- 참고자료: https://jojoldu.tistory.com/536
- hibernate 내부 구현상, 필드를 하나하나 비교하며 동등성을 따져 dirty check를 진행하는데, 동등성 비교가 불가능한 (equals/hashcode가 오버라이딩 되지 않은) 필드에 대해서는 객체 레퍼런스를 통해 비교한다고 하네요. 이 부분을 수정하였습니다. 
- equals/hashcode 오버라이딩은 `@EqualsAndHashCode` 롬복을 통해 비교합니다. 
-  By default, it'll use all non-static, non-transient fields, but you can modify which fields are used 라고 하네요. 
- 각 필드들이 같다면 확보되면 동등/동일한 것으로 간주하도록 재정의하도록 구성됩니다. 
- 참고자료: https://projectlombok.org/features/EqualsAndHashCode
- 나중에 엔티티들에 대해 hashcode/equals를 어떻게 가져갈지 같이 논의해봅시다
=> refactor: TicketMetadata hashcode/equals 정의

src/main/java/com/backend/connectable/klip/service/KlipService.java, src/main/java/com/backend/connectable/user/domain/User.java
- KLIP 에서 받아와 유저에 저장할때 소문자로 통일하도록 변경합니다!
=> fix: KLIP 주소를 소문자로 통일

src/main/java/com/backend/connectable/security/JwtAuthenticationFilter.java, src/main/java/com/backend/connectable/security/JwtProvider.java, src/main/resources/application.yml, src/test/java/com/backend/connectable/security/JwtProviderTest.java
1. **JwtProvider 에서 어드민 토큰에 대해 토큰 검증 기능을 추가했습니다**
- admin 토큰에 대해 payload가 같아야만 통과 가능하도록 구현했습니다.
- 이렇게 되면 payload가 민감정보가 되니 파라미터 스토어에 등록해 두었습니다. 
- jwt secret도 민감정보이니, prod 배포전에 파라미터 스토어로 이전하지요!
- 민감정보 분류도 기술 부채인듯합니다 :)
2. **어드민 토큰을 검증할 수 있도록 Filter에 로직을 추가했습니다**
- 원래 계획은 Interceptor를 통해서 검증할려했으나, 검증 로직을 Security에 몰아두는 것이 더 나은 방법이라고 판단하여 다음과 같이 작성하였습니다. 
- Interceptor를 통한 인증/인가 방식은 어드민 레포에서 확인 가능합니다. 
- https://github.com/Team-UACC/connectable-admin/tree/master/src/main/java/fans/connectable/admin/auth
- 우선은 /admin 요청에 대해서 verifyAdmin() 함수를 호출하여 검사하는 방식을 채택했습니다만,,, 최선의 방법인지는 모르겠네요. 피드백해주시면 감사하겠습니다! (시큐리티 어려워!)
=> feat: admin 토큰 검증 로직 구현

src/main/java/com/backend/connectable/DataLoader.java, src/main/java/com/backend/connectable/admin/service/AdminService.java, src/main/java/com/backend/connectable/event/domain/Ticket.java, src/main/java/com/backend/connectable/order/domain/OrderDetail.java, src/main/resources/application.yml, src/test/java/com/backend/connectable/admin/service/AdminServiceTest.java, src/test/java/com/backend/connectable/order/domain/OrderDetailTest.java
1. **티켓 전송을 블록체인 상에서 한 후에, Entity에 이를 반영을 안했네요!!!!**
- 블록체인 상에서 nft 전송이 완료된 후에, hash 값을 orderDetail에 저장합니다. 
- 티켓의 주인이 주문자로 바뀌었으니, 엔티티 연관관계 매핑을 진행합니다. 
- 어드민에서 한번 쓱 해봤는데 전송 잘 되더군요! 내일 같이 봐봅시다 :)
2. **민감 정보 => 파라미터 스토어로 넘기자**
- jwt secret을 파라미터 스토어에서 관리합시다!
=> fix: 티켓 전송 엔티티 반영 로직 추가

src/main/java/com/backend/connectable/event/domain/Ticket.java, src/main/java/com/backend/connectable/event/domain/TicketSalesStatus.java, src/main/java/com/backend/connectable/order/domain/OrderDetail.java, src/main/java/com/backend/connectable/order/service/OrderService.java, src/test/java/com/backend/connectable/admin/service/AdminServiceTest.java, src/test/java/com/backend/connectable/order/domain/OrderDetailTest.java, src/test/java/com/backend/connectable/order/service/OrderServiceTest.java
1. **티켓 주문 시 TicketSalesStatus 변경** 
- ON_SALE => PENDING
2. **어드민에서 OrderDetail 정보 변경 시 TicketSalesStatus 변경**
- PAID의 경우 : PENDING => SOLD_OUT
- UNPAID | REFUND의 경우 : PENDING => ON_SALE
- 위에 제시된 시나리오가 아니면 예외가 발생합니다. 예외 처리 전략 수립시 리팩터링 필요.
=> feat: TicketSalesStatus 정보 동기화

src/main/java/com/backend/connectable/artist/domain/Artist.java, src/main/java/com/backend/connectable/event/domain/Event.java, src/main/java/com/backend/connectable/event/domain/Ticket.java, src/main/java/com/backend/connectable/event/domain/repository/EventRepository.java, src/main/java/com/backend/connectable/event/domain/repository/TicketRepository.java, src/main/java/com/backend/connectable/event/service/EventService.java, src/main/java/com/backend/connectable/kas/service/KasService.java, src/main/java/com/backend/connectable/kas/service/dto/TokensResponse.java, src/main/java/com/backend/connectable/order/domain/Order.java, src/main/java/com/backend/connectable/user/domain/User.java, src/main/java/com/backend/connectable/user/service/UserService.java, src/main/java/com/backend/connectable/user/ui/dto/UserTicketResponse.java, src/test/java/com/backend/connectable/event/domain/repository/EventRepositoryTest.java, src/test/java/com/backend/connectable/event/domain/repository/TicketRepositoryTest.java, src/test/java/com/backend/connectable/kas/service/KasServiceTest.java, src/test/java/com/backend/connectable/user/service/UserServiceTest.java
1. **KAS 에서 사용자의 티켓(토큰) 정보를 가져오도록 리팩터링합니다**
- Flow는 다음과 같이 흘러갑니다
- EventRepository 에서 ContractAddress 싹다 조회
- KAS에 각 ContractAddress 별로 userKlaytnAddress에 대응되는 토큰이 있는지 API 호출
- 결과값에서 tokenUri를 추출 
- TicketRepository 에서 List<String\> tokenUris를 포함하는 친구들을 추출하여 List<Ticket\> 만듦
- 여기서 JPQL을 통해 JoinFetch를 2번 써서 Ticket/Event/Artist를 한번에 땡겨옵니다
2. **엔티티의 ID를 기반으로 equals/hashcode 를 재정의합니다**
- 아 KAS 테스트하기 너무 어렵네요ㅜㅜㅜㅜㅜ 테스트하기 어려운 코드에 대해 테스트를 어찌할지 고민해봅시다!
- Dev 서버에 올라가야 제대로 테스트할 수 있을듯합니다,,,ㅜ
=> refactor: KAS를 통해 사용자 티켓 정보 조회

src/main/java/com/backend/connectable/DataLoader.java, src/main/java/com/backend/connectable/event/ui/dto/TicketMetadataResponse.java, src/main/java/com/backend/connectable/kas/service/KasService.java, src/main/java/com/backend/connectable/s3/service/S3Service.java, src/main/resources/application.yml, src/test/java/com/backend/connectable/s3/service/S3ServiceTest.java
1. **KasService와 S3Service를 사용하여 새로운 티켓 민팅 기능을 데이터로더에 구현했습니다.**
- 아마 MVP에서는 데이터 로더에 작성한 로직처럼 NFT를 민팅하고자 합니다. 
- 미리 토큰 image와 토큰 uri를 만들어 S3에 업로드 한 후,
- KasService에서 Contract를 만들어 클레이튼에 배포하고
- KasService에서 Token을 1번 부터 차곡차곡 배포합니다. 
- 나중에 어드민에서 해당 기능을 제공할 수 있도록 추후 기능 개발이 필요해보입니다. 
2. **S3Service를 구현합니다**
- S3에서 토큰 uri를 가져옵니다. 
- 현재로써는 그냥 url을 넣으면 정보를 가져오는 수준입니다. 
- 나중에 이미지를 s3에 바로 업로드하는 기능등을 해당 클래스에 구현하면 좋을 듯 합니다. 
3. **Dataloader를 실행시킬지를 yaml에서 관리합니다**
- yml 에 dataloader.enable 이라는 항목을 뒀습니다.
- 파라미터 스토어에서 true/false를 제공하여 실제로 이를 구동 시킬지 말지를 결정하면 될 듯 합니다.
=> feat: dataloader에서 새로운 nft 발행기능 구현

src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryImpl.java, src/main/java/com/backend/connectable/event/service/EventService.java, src/test/java/com/backend/connectable/s3/service/S3ServiceTest.java
1. 이벤트 목록 조회시 EXPIRED 가 하위에 위치하도록 정렬
* [Reference](https://www.baeldung.com/spring-data-sorting)를 참고하여, SalesTo 순으로 내림차순 정렬하였습니다. 
2. 티켓 목록 조회 시 ON_SALE(판매중), PENDING(유저가 구매폼 제출시), SOLD_OUT(판매완료), EXPIRED(이벤트 종료시) 순서로 INT VALUE를 주어 정렬되도록 하였습니다. 
* [상기](https://stackoverflow.com/questions/67447083/querydsl-orderby-specific-string-values) 링크를 참고하여 작성하였습니다.
- 추후 시간별 정렬 순서에 대한 테스트 코드를 추가해보면 좋을 것 같습니다.
=> feat: 티켓 및 이벤트 정렬

src/main/java/com/backend/connectable/admin/service/AdminService.java, src/main/java/com/backend/connectable/event/domain/TicketMetadataConverter.java, src/main/java/com/backend/connectable/event/domain/TicketSalesStatus.java, src/main/java/com/backend/connectable/exception/ErrorType.java, src/main/java/com/backend/connectable/exception/GlobalExceptionHandler.java, src/main/java/com/backend/connectable/kas/service/KasService.java, src/main/java/com/backend/connectable/order/domain/OrderStatus.java, src/main/java/com/backend/connectable/s3/service/S3Service.java, src/main/java/com/backend/connectable/security/CustomUserDetailsService.java, src/main/java/com/backend/connectable/security/JwtProvider.java, src/test/java/com/backend/connectable/order/domain/OrderDetailTest.java, src/test/java/com/backend/connectable/security/JwtProviderTest.java
1. **예외 처리 전략을 수립하였습니다.**
- Enum으로 ErrorType을 관리합니다. 
- RuntimeException을 상속받은 ConnectableException을 정의해, HttpStatus와 ErrorType을 필드로 가지게 합니다. 
- 전역 ControllerAdvice에서 Exception을 잡아 ResponseEntity로 상태 코드와 바디를 응답해줍니다. 
2. **ControllerAdvice에서 예외를 잡아 처리합니다**
- 서비스에서 정의한 아래와 같은 예외를 처리합니다.
- ConnectableException
- KasException
- MethodArgumentNotValidException
- 서비스에서 정의한 예외를 벗어난 예외라면 Exception을 잡는 핸들러에서 처리합니다. 
- 이 과정에서 error 레벨로 예외에 대한 스택 트레이스를 로그로 기록합니다.
=> refactor: 예외 처리 전략 수립

src/main/java/com/backend/connectable/event/service/EventService.java, src/main/java/com/backend/connectable/event/ui/dto/EventDetailResponse.java, src/main/java/com/backend/connectable/global/common/util/OpenseaCollectionNamingUtil.java, src/test/java/com/backend/connectable/global/common/util/OpenseaCollectionNamingUtilTest.java, src/test/java/com/backend/connectable/kas/service/KasServiceTest.java
1. **KasService에서 ContractAddress를 통해 Contract 정보를 가지고 옵니다**
- 가지고 온 Contract 정보에서 Name을 추출한 뒤, 이를 Opensea Collection Url 정보에 맞게 바꿔줍니다. 
2. **관심사의 분리를 위해 OpenseaCollectionNamingUtil을 만들었습니다**
- 컬렉션에 대응되는 opensea url을 opensea의 현재 규격에 맞게 변환하는 util클래스를 따로 global/common에 분리하여 구현하였습니다. 
- 매번 KAS를 찔러 Contract 정보 가져오는건 비효율적입니다! 초장부터 Event 저장에 Contract Name을 같이 저장하도록 리팩터링이 필요합니다. Todo로 작성해뒀습니다~
=> refactor: Opensea Collection Url 추가

src/main/java/com/backend/connectable/admin/service/AdminService.java, src/main/java/com/backend/connectable/event/domain/repository/TicketRepositoryImpl.java, src/main/java/com/backend/connectable/event/service/EventService.java, src/main/java/com/backend/connectable/order/service/OrderService.java, src/main/java/com/backend/connectable/schedule/ScheduledTasks.java, src/main/java/com/backend/connectable/user/domain/User.java, src/main/java/com/backend/connectable/user/domain/repository/UserRepositoryCustom.java, src/main/java/com/backend/connectable/user/domain/repository/UserRepositoryImpl.java, src/main/java/com/backend/connectable/user/service/UserService.java, src/test/java/com/backend/connectable/global/common/util/OpenseaCollectionNamingUtilTest.java, src/test/java/com/backend/connectable/user/service/UserServiceTest.java
- 클래스 단위는 읽기 전용 Connection 맺도록 변경 및, 쓰기단위는 메소드 단위로 Transactional 어노테이션 붙임
- 모든 Transactional 어노테이션은 비즈니스 로직에 붙도록 함.
- 단건 As-Is : QueryDsl , To-Be : Dirty Checking
변경 사항등에 대해서는 Tech Spec 문서에 기입하였습니다. [링크 바로가기](https://www.notion.so/Transaction-fbb9388c6cd943abb75c60d131dc4292)
- 로직 변경으로 getOwnTicketsByUser 메소드 사용하지 않음에 따라 삭제 처리함
+) Dirty-Checking 방식이 이슈 없을 경우 UserService > modifyUser도 삭제 예정
- CheckedException ( SQLException, ... ) 에 대해서는 롤백되지 않는 부분에 대한 고민 필요
- 이외의 Unique Key, FK 등의 이슈에 대한 전반적인 점검 필요
=> refactor: 트랜잭션 어노테이션 정책에 따라 변경 및 단건 더티체킹

src/main/java/com/backend/connectable/user/domain/User.java, src/main/java/com/backend/connectable/user/service/UserService.java, src/test/java/com/backend/connectable/user/service/UserServiceTest.java
- Dirty Checking이 동작하지 않음으로, QueryDsl 을 사용하여 유저 수정하도록 변경
- 인증/인가 과정에서 SimpleJpaRepository를 사용하여 readOnly 옵션을 사용함에 따라 , 유저 엔티티 정보를 스냅샷으로 찍지않기에 더티 체킹이 동작하지 않음
- 해서, QueryDsl 로 쿼리가 수행되도록 함.
=> fix: 유저 수정 queryDsl 로 변경

src/main/resources/application.yml, src/main/resources/logback-spring.xml
1. **로깅 전략을 수립합니다**
- 재사용할 수 있는 logback appender를 만들었습니다. 
- sql_log/info_log/error_log를 각각 최근 7일 동안만 서버에 저장해두도록 xml을 설정했습니다
- Error 레벨의 로그가 발생한다면 slack에 웹훅을 통해 알림을 줍니다. 
- 주문이 들어오는 슬랙채널과 Dev Error 로그 발생시 알림을 주는 슬랙채널을 분리해야한다고 생각하여 이를 분리하였습니다. 주의 사항에 삽질 조금 적었습니다. 
2. **Dev서버에 로그를 대량으로 찍어둡니다**
- 실시간 디버깅으로는 orm, transaction, hikari 등의 액션을 정확히 보기 힘들어 해당 로그를 Trace 레벨까지 찍어두도록 합니다. 
- 참고: https://github.com/inbonk/exception-handling-in-nested-transactional-classes/blob/master/src/main/resources/application.yml
- 아... logback-spring.xml에서 application.yml 정보 읽어오는 방법을 몰라서 한참 걸렸네요. 아래와 같이 쓰면 됩니다. 
```xml
<springProfile name="slack-paid-logging">
<springProperty name="devPaidSlackUri" source="logging.slack.webhook-uri-dev-paid" />
<appender name="DEV_PAID_USER_SLACK_NOTI" …
```
=> feat: 로깅 전략 수립

src/main/java/com/backend/connectable/order/service/OrderService.java, src/main/java/com/backend/connectable/security/ConnectableUserDetails.java, src/main/java/com/backend/connectable/security/CustomUserDetailsService.java, src/main/java/com/backend/connectable/security/JwtAuthenticationFilter.java, src/main/java/com/backend/connectable/security/JwtProvider.java, src/main/java/com/backend/connectable/security/SecurityConfiguration.java, src/main/java/com/backend/connectable/security/exception/ConnectableSecurityException.java, src/main/java/com/backend/connectable/user/domain/User.java, src/main/java/com/backend/connectable/user/domain/repository/UserRepositoryCustom.java, src/main/java/com/backend/connectable/user/domain/repository/UserRepositoryImpl.java, src/main/java/com/backend/connectable/user/service/UserService.java, src/main/resources/application.yml, src/test/java/com/backend/connectable/order/service/OrderServiceTest.java, src/test/java/com/backend/connectable/security/JwtProviderTest.java, src/test/java/com/backend/connectable/security/exception/ConnectableSecurityExceptionTest.java, src/test/java/com/backend/connectable/user/service/UserServiceTest.java
1. **UserDetails가 klaytnAddress만을 들고 있도록 리팩터링**
- 오전에 설명했던 것 처럼, Spring Security에서 UserDetails에 User 엔티티를 담아봤자 Spring MVC에 도착하고 나서는 영속성 컨텍스트의 혜택을 받지 못해요. 
- 이유는 Filter 단에서 User 엔티티 정보를 가져와 영속성 컨텍스트에 영속화 시켜놨더니만,,,
- 정작 Open Session In View는 Spring MVC의 Interceptor 부터 열리기 시작해서 (새로운 엔티티 매니저 오픈!)
- 기존에 Spring Security의 SecurityContext에 넣어뒀던 UserDetails의 경우, **준영속** 상태에 빠지게 되고 
- 그에 따라, 준영속 상태가 되버린 User 엔티티로는 영속성 컨텍스트의 혜택을 받지못하는데, 여기서 혜택은 1차캐시, 변경 감지를 뜻하고
- 따라서 준영속 상태의 User 엔티티로는 기존의 modify 도메인 로직의 변경 감지가 안먹혔던 겁니다. 🥲
- 따라서 UserDetails는 klaytnAddress만을 들고 있게 변경하였고, Service단에 들어와서 다시 User를 조회하여 영속성 컨텍스트의 혜택을 받을 수 있도록! JPA를 JPA 처럼 쓸 수 있도록 리팩터링 했습니다. 
- 없앴던 User 정보 변경해주는 도메인 로직도 부활시켰습니다. 
2. **Spring Security에서의 예외처리**
- 삽질 좀 했습니다. 주의 사항에 삽질 과정 적어두겠습니다. 
- 현재 구현은 다음과 같이 이뤄집니다. 
- …
=> refactor: user details 수정

src/main/java/com/backend/connectable/order/domain/OrderDetail.java
- @XToOne을 LAZY로 사용하는 경우, @XToMany를 EAGER로 사용하는 경우에만 명시하기로 내부 정책 정함.
=> refactor: 정책에 따라 fetchType 명시 제거

Dockerfile, Jenkinsfile
- 각각 dev/master가 다른 profile로 구동되도록 docker image 빌드 시점에 지정합니다. 
- 참고: https://stackoverflow.com/questions/34324277/how-to-pass-arg-value-to-entrypoint
=> refactor: dockerfile profile 적용

build.gradle, src/main/java/com/backend/connectable/DataLoader.java, src/main/java/com/backend/connectable/event/domain/Ticket.java, src/main/java/com/backend/connectable/exception/ErrorType.java, src/main/java/com/backend/connectable/order/domain/OrderDetail.java, src/main/java/com/backend/connectable/user/ui/dto/UserResponse.java, src/main/resources/application.yml, src/main/resources/db/migration/V1_1__init_constraints.sql, src/main/resources/db/migration/V1__init.sql, src/main/resources/db/migration/V2__add_ticket_is_used.sql, src/main/resources/db/migration/V3__remove_ticket_user_mapping.sql, src/test/java/com/backend/connectable/admin/service/AdminServiceTest.java, src/test/java/com/backend/connectable/event/domain/TicketTest.java, src/test/java/com/backend/connectable/event/domain/repository/EventRepositoryTest.java, src/test/java/com/backend/connectable/event/domain/repository/TicketRepositoryTest.java, src/test/java/com/backend/connectable/order/service/OrderServiceTest.java, src/test/java/com/backend/connectable/user/service/UserServiceTest.java
1. **Flyway를 도입합니다**
- DB 형상관리를 위해 Flyway를 도입합니다. 
- 현재 dev 서버에 있는 내용을 스냅샷으로 복사해 새로운 rds를 만든 후 테스트를 진행하고, 성공적으로 스키마가 변경되었습니다. 
2. **Ticket에 isUsed 필드를 추가합니다**
- NFT와 1:1 매핑되는 Ticket 엔티티에 isUsed 필드를 추가합니다. 
- 해당 필드로 입장관리를 할 예정입니다 
3. **Ticket과 User의 연관관계를 끊습니다**
- 연관이 없어진 두 엔티티의 연관관계를 끊어뒀습니다. 
- 이제 ddl-auto 전략을 prod/dev 모두 none => validate로 바꾸는 것이 좋아보입니다!
=> feat: flyway 도입

src/main/java/com/backend/connectable/event/domain/dto/EventTicket.java, src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryImpl.java, src/main/java/com/backend/connectable/event/service/EventService.java, src/main/java/com/backend/connectable/event/ui/dto/TicketResponse.java, src/test/java/com/backend/connectable/event/ui/EventControllerTest.java
- TicketResponse dto에 isUsed 필드를 추가합니다
- 이를 통해 사용된 티켓의 경우 입장 QR을 생성하지 않도록 합니다!
- EventMapper에 의존적인 Dto 변환로직입니다. isUsed 필드를 getIsUsed() 메서드로 빼줘야 매핑이 되더라고요!
=> refactor: TicketResponse isUsed 필드 추가

src/main/java/com/backend/connectable/event/domain/Event.java, src/main/java/com/backend/connectable/event/domain/dto/EventDetail.java, src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryImpl.java, src/main/java/com/backend/connectable/event/mapper/EventMapper.java, src/main/java/com/backend/connectable/event/service/EventService.java, src/main/java/com/backend/connectable/event/ui/dto/EventDetailResponse.java, src/main/resources/db/migration/V4__add_event_contract_name.sql, src/test/java/com/backend/connectable/event/ui/EventControllerTest.java
- Todo로 남겨뒀던, 그 동안은 KAS를 찔러 가져오던 ContractName을 DB에 저장합니다. 
- 관련 로직에 대해 EventMapper 와 QueryDsl에 약간의 수정이 들어갔습니다. 
- EventMapper에서 TicketToResponse를 변환해줄 때, ownedBy를 무시하여 변환하도록 어노테이션 하나 추가했습니다!
- 이건 어차피 KAS 갔다와야하는 로직이라 EventMapper 단에서 해결할 수 없는건데, 계속 빌드시 워닝이 나와서 해당 어노테이션 추가했습니다!
- Flyway 반영했습니다. Dev 머지되고나서, 직접 쿼리 날려서 Contract name 채워 넣을게요!
- Flyway 잘 되겠지...?
=> refactor: DB에서 ContractName을 가지도록 수정

src/main/java/com/backend/connectable/event/domain/Ticket.java, src/main/java/com/backend/connectable/exception/ErrorType.java, src/main/java/com/backend/connectable/user/redis/UserTicketEntrance.java, src/main/java/com/backend/connectable/user/service/UserService.java, src/main/java/com/backend/connectable/user/service/UserTicketService.java, src/main/java/com/backend/connectable/user/ui/UserController.java, src/main/java/com/backend/connectable/user/ui/dto/UserTicketEntranceRequest.java, src/main/java/com/backend/connectable/user/ui/dto/UserTicketEntranceResponse.java, src/main/resources/application.yml, src/test/java/com/backend/connectable/event/domain/TicketTest.java, src/test/java/com/backend/connectable/user/service/UserServiceTest.java
1. **티켓 입장 기능을 구현합니다**
- API 명세에 따라 티켓 입장 기능을 구현하였습니다
- redis에서 정보 가져와서 비교하여 구현합니다 
- 해당 입장 인증 관련 정보를 저장하는 redis는 60초 만료 시간 설정해두었습니다
2. **userService에 티켓 관련 정보를 userTicketService로 따로 분류했습니다**
- 너무 방대해지는 로직을 userTicketService에 따로 관리합니다
=> feat: 티켓 입장 기능 구현

src/main/java/com/backend/connectable/user/service/UserService.java, src/test/java/com/backend/connectable/user/service/UserServiceTest.java
- Transcational 어노테이션으로 변경감지 지원하도록 합니다!
- Transactional(ReadOnly=true)는 변경감지 혜택을 못받는다고 하군요..!
- 엔티티 변경에 있어서는 Transactional 빼놓지 않고 써야겠습니다
=> fix: 티켓 사용 여부 로직에 Transactional 추가

src/main/java/com/backend/connectable/event/domain/repository/TicketRepositoryCustom.java, src/main/java/com/backend/connectable/event/domain/repository/TicketRepositoryImpl.java, src/main/java/com/backend/connectable/order/service/OrderService.java, src/main/java/com/backend/connectable/order/ui/dto/OrderRequest.java, src/test/java/com/backend/connectable/event/domain/repository/TicketRepositoryTest.java, src/test/java/com/backend/connectable/order/service/OrderServiceTest.java
- 구매시 List<ticketId\>에 0 하나만 있다면 eventId에 대응되는 이벤트의 티켓 중 on_sale인 친구 중 하나를 찾아 이를 구매 요청으로 넘깁니다. 
- 덕분에 querydsl 처음 커밋해봅니다
- 웰컴 티켓 인당 구매 한번인데 이거 어찌 막지...?
=> feat: 무작위 티켓 구매 로직 구현

src/main/java/com/backend/connectable/event/domain/repository/TicketRepository.java, src/main/java/com/backend/connectable/event/domain/repository/TicketRepositoryCustom.java, src/main/java/com/backend/connectable/event/service/EventService.java, src/main/java/com/backend/connectable/kas/service/dto/TokenIdentifier.java, src/main/java/com/backend/connectable/kas/service/dto/TokensResponse.java, src/test/java/com/backend/connectable/event/domain/repository/TicketRepositoryTest.java, src/test/java/com/backend/connectable/kas/service/dto/TokenIdentifierTest.java
=> fix: 유저 토큰 조회시 id와 uri 검증하도록 수정

src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryCustom.java, src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryImpl.java, src/main/java/com/backend/connectable/event/service/EventService.java, src/test/java/com/backend/connectable/event/domain/repository/EventRepositoryTest.java
- 판매중인 이벤트가 상단에 우선 위치
- 판매중인 이벤트에 대해서는 이벤트 종료일 순서로 오름차순 배치 
`
SELECT
event.*
FROM
event
ORDER BY
CASE
WHEN event.sales_to > NOW() THEN 1
ELSE 2
END ASC,
event.sales_to ASC
`
쿼리 참고 부탁드립니다 :) 🙏
=> feat: 이벤트 목록 조회 순서 변경

src/main/java/com/backend/connectable/admin/service/AdminService.java, src/main/java/com/backend/connectable/auth/service/AuthService.java, src/main/java/com/backend/connectable/sms/config/SmsConfig.java, src/main/java/com/backend/connectable/sms/service/MessageContent.java, src/main/java/com/backend/connectable/sms/service/SmsService.java, src/main/resources/application.yml, src/test/java/com/backend/connectable/admin/service/AdminServiceTest.java
- 티켓 비용 입금 확인 시 문자로 전송
- 인증부와 주문쪽에서 모두 SMS 를 사용하여 SMS Service로 뺐습니다.
- 현재 SMS Test 키가 제공되지 않아, 로컬에서 사용하는 키를 분리하여 비활성화/활성화 switch 가능케끔 하였습니다. 
- CLI를 사용하는 방안등에 대해 고려해보았으나, Production과 유사한 방향으로 가는게 맞다 생각하여 yaml에서 관리되게끔 하였는데, 관련하여 local 환경에서 secret 관리를 하는 best-practice가 있다면 의견 부탁드리겠습니다.
=> feat: 티켓 구매시 문자 발송

src/main/resources/application.yml, src/main/resources/logback-spring.xml, src/test/java/com/backend/connectable/kas/service/testnet/KasServiceTestWithTestnet.java
**1. 로컬 KAS 파라미터 스토어 도입합니다**
- 로컬 테스트에서 사용할 KAS 정보도 민감정보로 분류하여 파라미터 스토어 도입했습니다
- 기존에 쓰던 Authentication 정보 삭제하고 새로 발급받아 저장해뒀습니다
- 알려주신대로 파라미터 스토어 정보 로컬에서 사용하도록 구축했습니다~ 감사합니다
**2. 콘솔 로깅에 쓰레드 정보를 기입합니다**
- 비동기 처리에 어떤 쓰레드가 사용되는지 쓰레드 정보를 로깅할 필요가 있어보여서 도입합니다. 
**3. KasServiceTestWithTestnet에서 발행하는 tokenId 랜덤값 범위를 늘립니다**
- 테스트를 많이 돌리다보니, 랜덤으로 생성한 숫자가 이미 있는 숫자라는 응답이 오더군요
- 테스트 상에서 원래 `000~999` 까지였던 범위를 `0000~9999`로 늘립니다
=> refactor: 로컬 KAS 파라미터 스토어 도입

src/test/java/com/backend/connectable/acceptance/AuthAcceptanceTest.java, src/test/java/com/backend/connectable/auth/service/AuthServiceTest.java, src/test/java/com/backend/connectable/auth/ui/AuthControllerTest.java
- 문자 인증을 받는 부분의 인증 기능 테스트 작성 추가하였습니다.
- 인증키를 받고, 해당 키로 인증 성공하는 것까지의 시나리오만을 인수테스트 진행하였습니다.
- 단위 테스트 > 통합 테스트 > 인수 테스트 순으로 테스트 개수를 가지도록 하였습니다. 
- [마틴 파울러의 피라미드](https://martinfowler.com/articles/practical-test-pyramid.html) 를 따랐는데요, 인수테스트나 통합테스트가 무거워질수록 빌드타임에 영향을 끼칠듯 하여 서비스 레이어 테스트를 풍부하게 가는 기조로 작성했습니다.  
1. private 메소드를 테스트 하는 것에 대한 고민
private method를 테스트 하는 것을 고민해보았습니다.
```
@DisplayName("인증키 생성시마다 랜덤한 문자열이 생성된다.")
@Test
void generateCertificationKey()
throws NoSuchMethodException, InvocationTargetException, IllegalAccessException {
// given & when
Method method = AuthService.class.getDeclaredMethod("generateCertificationKey");
method.setAccessible(true);
String actual1 = (String) method.invoke(authService);
String actual2 = (String) method.invoke(authService);
// then …
```
=> test: 가입시 인증 로직 테스트 코드 작성

src/main/java/com/backend/connectable/kas/config/KasWebClientConfiguration.java
1. **계속 발생하는 하나의 에러 메시지**
- 우리 슬랙에 계속 오는 에러 알람이 하나 있는데요. 아래 에러와 같아요. 
```
19:54:04.891 [ERROR] [reactor-http-epoll-4] [reactor.core.publisher.Operators] - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: org.springframework.web.reactive.function.client.WebClientRequestException: readAddress(..) failed: Connection reset by peer; 
nested exception is io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
Caused by: org.springframework.web.reactive.function.client.WebClientRequestException: readAddress(..) failed: Connection reset by peer; 
nested exception is io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
at …
```
=> fix: Http Keep-Alive 설정 부여

src/main/java/com/backend/connectable/kas/service/contract/KasContractService.java, src/test/java/com/backend/connectable/acceptance/AuthAcceptanceTest.java, src/test/java/com/backend/connectable/auth/service/AuthServiceTest.java, src/test/java/com/backend/connectable/auth/ui/AuthControllerTest.java, src/test/java/com/backend/connectable/kas/service/KasServiceTest.java, src/test/java/com/backend/connectable/order/ui/OrderControllerTest.java, src/test/java/com/backend/connectable/security/custom/JwtAuthenticationFilterTest.java
- Order 쪽 Controller 테스트가 부족한 듯 하여 추가했습니다.
- WithUserDetails를 사용하여 임의의 UserDetails를 가져와 사용할 수 있도록 하였습니다.
- 필요한 Bean 들을 쉽게 가져오려고 AutoConfigureMvc, SpringBootTest를 사용하였습니다. 
- ControllerTest 에서는 User 객체를 쉽게 반환할 수 있어 WithUserDetails가 좋은 것 같아요 ㅎㅎ( 셋업에서 간단하게 유저 등록 후 사용할 수 있기에 )
**참고**
- [Spring Security가 적용된 곳을 효율적으로 테스트하자](https://tecoble.techcourse.co.kr/post/2020-09-30-spring-security-test/)
- [Testing Method Security](https://docs.spring.io/spring-security/site/docs/5.0.x/reference/html/test-method.html)
=> test: OrderControllerTest 추가

build.gradle
- **Jacoco를 도입합니다**
- Line Coverage 80%를 못넘기면 테스트가 실패하도록 -> 빌드가 실패하도록 구성했습니다. (현재 라인 커버리지 84%)
- 점진적으로 커버리지 올라가면 빌드 하한선을 높여가면 될 것 같네요. 
- 빌드하시고 build/reports/jacoco/test/html/index.html 에 들어가시면 리포트 볼 수 있습니다. (혹시 리포트 path를 바꾸고 싶으시다거나, csv/xml 리포트가 필요하다고 생각하시면 얘기해주세요!) 
- Qdomain의 경우 커버리지 계산에서 제외했습니다!
- *참고: https://techblog.woowahan.com/2661/*
=> build: jacoco 도입

src/main/java/com/backend/connectable/admin/ui/AdminController.java, src/test/java/com/backend/connectable/acceptance/AdminAcceptanceTest.java, src/test/java/com/backend/connectable/fixture/EventFixture.java
1. **어드민 인수테스트를 작성합니다**
- 테스트 하기 까다로운 Kas의 경우, Netty Mockserver를 통해 구현해둔 KasServiceMockSetup 클래스를 재활용하여 구현합니다. 
- 외부모듈이 많아질 수록 테스트하기가 참 어렵다는걸 많이 느끼네요. 
- <img width="670" alt="스크린샷 2022-10-09 오후 3 35 19" src="https://user-images.githubusercontent.com/61370901/194741808-2db5c63c-e630-481d-be25-22bdc1014642.png">
- 다양한 로직과 기능들이 섞여있는 Admin 이다보니 인수테스트를 작성하면서 몇가지 문제점이 눈에 띄었습니다. 
- SmsService의 경우 테스트 코드에 유효한 핸드폰 번호를 입력했을때, 진짜 문자가 가는 상황이 발생하더라고요. 
- 지금은 테스트 코드에 유효하지 않은 번호를 기입해뒀기 때문에 누군가가 문자를 받진 않겠지만, 테스트 코드를 돌릴때 마다 누리고에서 해당 번호로 문자 보내고 문자 50원이 차감되지는 않나 걱정이되더라고요. 
- 따라서 테스트에서는 진짜 SmsService를 쓰지 않도록 테스트 코드 개선이 필요해보입니다. 
- 생각나는 방법이 몇가지 있긴한데요. 
1. SmsService가 들어가는 모든 테스트코드에 MockBean 설정하기
2. SmsService를 인터페이스화 시켜서, 테스트에서만 사용할 SmsService 구현체를 만들어 테스트 진행하기
3. Bean으로 생성하는 SmsConfig내의 …
=> test: 어드민 인수테스트 작성

README.md, src/test/java/com/backend/connectable/acceptance/UserAcceptanceTest.java, src/test/java/com/backend/connectable/fixture/KlipFixture.java, src/test/java/com/backend/connectable/fixture/RequestKeyRequest.java, src/test/java/com/backend/connectable/fixture/RequestKeyResponse.java, src/test/java/com/backend/connectable/user/ui/UserControllerTest.java
- Request key가 유효하지 않은 경우 네트워크 에러 발생 현상 수정
- KlipFixture에서 RestTemplate으로 Klip API '/prepare' 엔드포인트 호출후 응답 반환
- 기존 시나리오에서는 request-key로 생성된 QR코드를 찍어야 status 가 prepared -> requested -> completed로 넘어감
- 테스트 코드에서 KlipService.authLogin에서 QR인증이 되지 않은 request key에 대해 jwt를 내려주지 않아 임의로 모킹함
- 필드명 SNAKE_CASE <-> camelCase 불일치 이슈(응답값이 null로 받아짐)로 @JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class) 사용
- 더 좋은 방법이 있다면 코멘트 부탁드립니다 :)
=> fix: Request key 이슈로 에러나는 현상 수정

src/main/java/com/backend/connectable/global/aop/MethodNameExtractor.java, src/main/java/com/backend/connectable/global/aop/TimeCheck.java, src/main/java/com/backend/connectable/global/aop/TimeCheckAspect.java, src/main/java/com/backend/connectable/kas/service/KasService.java
1. **AOP를 공부했습니다**
- 사실 AOP에 대한 이해가 많이 부족했습니다. AOP의 필요성에 대해서 입문하기 좋았던 글 첨부합니다. (https://tecoble.techcourse.co.kr/post/2021-06-25-aop-transaction/)
- 어쨋든 이 횡단 관심사를 그냥 OOP 방식으로 기능 구현하듯이 만들 수는 있겠지만, 오히려 재사용성이 떨어지는 일이 발생하는데요. 따라서 횡단 관심사를 처리할 수 있도록 AOP라는 기술을 씁니다. 
- 자바에서 AOP를 쓸라면 프록시라는 기술을 써야합니다. 
- 프록시는 실제 요청을 처리할 객체를 인스턴스 변수로 가지고 있고, 요청을 처리하기 전/후로 필요한 전처리/후처리를 진행하는 방식입니다. 
- 프록시는 리플렉션들과 같은 자바 고급기술들을 휘뚜루마뚜루 적용시켜 뚝딱 만드는데요. 크게 2가지 방식이 있습니다. 
- JdkDynamicProxy : 인터페이스가 있는 경우 쓸 수 있음 (자바 언어 내장기술)
- CGLIB : 구체 클래스를 상속받아서 만듦 (외부 라이브러리. 근데 스프링부트2.0 부터 디폴트로 이거 채택함)
- 이렇게 횡단 관심사 로직이 필요한 메서드가 포함된 빈에 대해서는, 어플리케이션 컨텍스트에 등록하기전에 해당 빈을 프록시화 하여 빈을 등록하게 됩니다. 
- 여기( https://github.com/joelonsw/TIL/blob/master/2022-10/2022-10-17.md#kasservice%EC%97%90-aop-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0 )에 1,2번을 보시면 제가 정의한 …
=> feat: TimeCheck AOP 도입

src/test/java/com/backend/connectable/acceptance/AdminAcceptanceTest.java, src/test/java/com/backend/connectable/acceptance/AuthAcceptanceTest.java, src/test/java/com/backend/connectable/acceptance/DatabaseCleanUp.java
- 인수 테스트 내 DirtiesContext 제거
- ApplicationContext가 메소드 단위로 재시작 되면서 속도가 느려짐 -> 인수테스트 코드 실행시 평균적으로 70s 소요됨
- DB Table Truncate 방식을 이용하여 ApplicationContext 재시작하지 않고 테스트를 위해 데이터 초기화를 진행함 -> 평균 40s 까지 속도 개선 진행 
- https://tecoble.techcourse.co.kr/post/2022-10-15-test-code-optimization/
=> refactor: DirtiesContext제거 하여 Truncate로 변경

build.gradle, src/main/java/com/backend/connectable/global/config/swagger/SwaggerConfig.java, src/main/resources/application.yml
1. **프로메테우스 + 그라파나 모니터링을 위해 코드레벨에서 actuator를 도입합니다**
- Spring Boot 모니터링/메트릭을 API 형식으로 확인할 수 있도록 지원하는 actuator 의존성, prometheus에 사용될 메트릭 정보를 수집하는 micrometer-registry-prometheus 의존성을 추가합니다. 
- Springfox (Swagger) 의존성이랑 충돌이 나는 부분이 있어서 이를 해결했습니다. (https://github.com/joelonsw/TIL/blob/master/2022-11/2022-11-05.md#spring-actuator%EC%99%80-springfox-%EC%B6%A9%EB%8F%8C)
- 해당 pr 머지 이후 dev 환경에서 프로메테우스 + 그라파나 구축을 시도해보겠습니다. 
- 우선 현재 설정으로 base_url/actuator에 접근하면 모든 사람들이 저희 서버의 메트릭을 다 볼 수 있어요
- 해당 url에 대해 인증/인가 로직이 있어야 할 것 같기도합니다...?!
- 혹시 현업에서 프로메테우스 + 그라파나 쓰실 때 모니터링을 위한 메트릭 조회 url을 막아뒀는지도 궁금합니다. 
- application.yml에 공통된 사항은 그냥 --- 기준 맨 위 블럭으로 옮겨도 될 것 같은데 저희가 프로파일 별로 중복된 것들 그냥 써두긴 했군요. 혹시나 나중에 너무 복잡해지면 리팩터링 해봅시다!
=> feat: 프로메테우스 actuator 도입

src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryCustom.java, src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryImpl.java, src/main/java/com/backend/connectable/event/service/EventService.java, src/main/java/com/backend/connectable/event/ui/EventController.java, src/test/java/com/backend/connectable/event/domain/repository/EventRepositoryTest.java, src/test/java/com/backend/connectable/event/service/EventServiceTest.java, src/test/java/com/backend/connectable/event/ui/EventControllerTest.java, src/test/java/com/backend/connectable/fixture/EventFixture.java, src/test/java/com/backend/connectable/fixture/TicketFixture.java
1. **오늘 구매 가능한 이벤트를 조회하는 API를 구현합니다**
- GET /events/today 엔드포인트를 통해 오늘 구매 가능한 이벤트를 조회합니다
- 이벤트의 salesTo 필드보다 현재 시각이 더 작다면 조회의 대상이 됩니다. 
- 레포지토리/서비스/컨트롤러 테스트 추가하여 작성하였습니다.
=> feat: 오늘 구매 가능한 이벤트 조회 API

src/main/java/com/backend/connectable/artist/domain/Comment.java, src/main/java/com/backend/connectable/artist/domain/dto/ArtistComment.java, src/main/java/com/backend/connectable/artist/domain/repository/CommentRepositoryCustom.java, src/main/java/com/backend/connectable/artist/domain/repository/CommentRepositoryImpl.java, src/main/java/com/backend/connectable/artist/mapper/ArtistMapper.java, src/main/java/com/backend/connectable/artist/service/ArtistService.java, src/main/java/com/backend/connectable/artist/ui/ArtistController.java, src/main/java/com/backend/connectable/exception/ErrorType.java, src/main/java/com/backend/connectable/security/config/SecurityConfiguration.java, src/main/resources/db/migration/V12__add_comment_is_deleted_column.sql, src/test/java/com/backend/connectable/artist/service/ArtistServiceTest.java, src/test/java/com/backend/connectable/artist/ui/ArtistControllerTest.java
- 아티스크 댓글 삭제 기능 추가
- Querydsl을 이용하여 Soft delete 처리
- @SQLDelete ( [link](https://www.jpa-buddy.com/blog/soft-deletion-in-hibernate-things-you-may-miss/)  ) 와 더티 체킹을 고려하다, 기존 user 엔티티 소프트 삭제 방법과 동일하게 QueryDsl 로 업데이트 치는 방향으로 처리하였습니다.  
- 관련하여 comment 테이블에 is_deleted 컬럼 추가가 진행됩니다.
- 작성자 판단 여부는 도메인에 질의하는 것이 적합하다 판단하여 isCommentAuthor 도메인에 질의합니다. 
void type으로 작성한 것이 꺼림직 한데, boolean 타입으로 변경 후 외부에서 Exception을 터트리는 것이 좋을지 피드백 부탁드립니다.. 🤗
- Artist가 삭제되는 등의 이유로 artistId 에 매핑되는 튜플이 존재하지 않을 경우 프론트에서 코멘트에서 댓글이 노출되지 않을 것이라 판단하여 로직 내 아티스트 검증 로직은 포함하지 않았습니다. 관련하여 생각치 못한 이슈 케이스가 존재할지 궁금합니다.. 찜찜하네요.
- artistId가 필요할까 고민하다 artist > comment 계층 구조를 가지고 있는걸 생각하면 URL Path에서 artistId도 같이 확인해야 하는게 맞는것 같기도 하고 아리송하네요.. 우선은 제가 생각할 때의 RestFul은 동일한 리소스에 대해 행동이 다르다면 URI는 같고 메소드는 달라야한다 라고 생각하여 DeleteMapping으로 동일 엔드포인트와 …
=> feat: 댓글 삭제 기능 추가

src/main/java/com/backend/connectable/artist/domain/Artist.java, src/main/java/com/backend/connectable/artist/domain/Notice.java, src/main/java/com/backend/connectable/artist/domain/NoticeStatus.java, src/main/java/com/backend/connectable/artist/domain/dto/ArtistDetail.java, src/main/java/com/backend/connectable/artist/domain/repository/ArtistRepository.java, src/main/java/com/backend/connectable/artist/domain/repository/ArtistRepositoryCustom.java, src/main/java/com/backend/connectable/artist/domain/repository/ArtistRepositoryImpl.java, src/main/java/com/backend/connectable/artist/domain/repository/NoticeRepository.java, src/main/java/com/backend/connectable/artist/mapper/ArtistMapper.java, src/main/java/com/backend/connectable/artist/service/ArtistService.java, src/main/java/com/backend/connectable/artist/ui/dto/ArtistDetailResponse.java, src/main/java/com/backend/connectable/artist/ui/dto/NoticeResponse.java, src/main/resources/db/migration/V13__add_notice_table_and_artist_columns.sql, src/test/java/com/backend/connectable/artist/service/ArtistServiceTest.java, src/test/java/com/backend/connectable/artist/ui/ArtistControllerTest.java, src/test/java/com/backend/connectable/event/ui/EventControllerTest.java, src/test/java/com/backend/connectable/fixture/ArtistFixture.java
- ArtistDetail 조회시 하기 필드가 추가되었습니다.
- twitterUrl, instagramUrl, webpageUrl, description, notice
- Notice 테이블이 추가되었습니다. 
- 추후 공지사항 노출/비노출을 고려하여 Enum 타입으로 공지사항 타입을 관리합니다.
- DDL 스크립트에 대한 상세한 검토 부탁드립니다. 🙏 
- artist 도메인에 대해 필드명에 artist가 포함되지 않는 것으로 조건이 변경되어 DTO 및 테스트 코드 내 필드명 변경하였습니다.
=> feat: 아티스트 상세 조회시 공지사항 및 추가정보 필드 추가

src/main/java/com/backend/connectable/exception/ErrorType.java, src/main/java/com/backend/connectable/exception/GlobalExceptionHandler.java, src/main/java/com/backend/connectable/exception/KasException.java, src/main/java/com/backend/connectable/exception/KasExceptionResponse.java, src/main/java/com/backend/connectable/kas/config/KasWebClient.java
1. **WebClient Timeout을 설정합니다**
- 문득 외부 KAS API가 장애가 발생해서 죽으면 어쩌지? 에 대한 고민을 해봤습니다.
- 물론 좋은건 블록체인 노드를 직접 운영하는 java 코드로 백업 플랜을 짜두는 것 같은데, 현 시점으론 불가능해보이고, 
- 최소한 API 조회가 안되면 Timeout error log라도 띄워서 우리가 인식할 수 있어야한다는 생각해 해당 기능을 추가합니다.
- 5초 안에 Reactive Stream 내에서 응답이 없다면 예외가 발생합니다!
2. **GlobalExceptionHandler의 예상치못한 Exception 핸들러를 수정합니다**
- 가끔 슬랙에 미친듯이 알람이 뜰때가 있는데요. 
- 스택트레이스를 String으로 한줄씩 .forEach() 에러레벨로 출력시키고 있더군요. 에러레벨의 로그가 찍히면 우리 슬랙으로 알림이 가니 그랬던 것 같습니다. 
- 스택트레이스 한줄로 압축해서 로그 남기도록 수정했습니다 :) 
- 외부 시스템 장애에 대해 대처하는 방법을 고민해볼 수 있는 글이 있어 공유합니당 (https://techblog.woowahan.com/6447/)
- 우리 Connectable 같은 경우, Kas 외부 모듈을 쓰는 기능들에서 장애의 영향을 받을 기능들은
- 컨트랙트 배포 및 토큰 민팅 -> 이건 정상화 후 수행해도 됨
- 사용자 토큰 구매시 전송해주기 -> 구매 내역은 RDB에 남으니, 정상화 된 후 보내준다고 공지해주기로 우선은 해결할 수 있어보임
- 내 티켓 조회하기 -> 대책이 필요해보임. 오프라인 모드를 통한 프론트엔드 캐싱? …
=> feat: WebClient timeout 설정
