Team-UACC/connectable-backend

- build.gradle
- src/main/java/com/backend/connectable/user/domain/User.java
- src/main/java/com/backend/connectable/user/domain/UserRepository.java
- src/main/java/com/backend/connectable/user/domain/UserRepositoryCustom.java
- src/main/java/com/backend/connectable/user/domain/UserRepositoryImpl.java
- src/test/java/com/backend/connectable/user/domain/UserRepositoryTest.java
- src/test/java/com/backend/connectable/user/domain/UserTest.java
- src/test/java/com/backend/connectable/user/ui/UserControllerTest.java
- queryDsl 적용 
- 불필요한 import 정리
> feat: queryDsl 적용

- build.gradle
- src/main/java/com/backend/connectable/security/JwtProvider.java
- src/main/resources/application.yml
- src/test/java/com/backend/connectable/security/JwtProviderTest.java
- jwt 토큰 생성
- jwt 토큰 검증 
- jwt 토큰 claim 추출 
- security에서 jwt 토큰 관리 방법 리서치 필요
> feat: jwt 토큰 생성 및 클레임 추출

- src/main/java/com/backend/connectable/user/domain/User.java
- src/main/java/com/backend/connectable/user/domain/UserRepository.java
- src/main/java/com/backend/connectable/user/domain/UserRepositoryCustom.java
- src/main/java/com/backend/connectable/user/domain/UserRepositoryImpl.java
- src/main/java/com/backend/connectable/user/service/UserService.java
- src/main/java/com/backend/connectable/user/ui/UserController.java
- src/main/java/com/backend/connectable/user/ui/dto/UserDeleteResponse.java
- src/test/java/com/backend/connectable/user/domain/UserRepositoryTest.java
- src/test/java/com/backend/connectable/user/service/UserServiceTest.java
- 유저 탈퇴 기능 추가 
- 유저 탈퇴 기능 테스트 코드 추가
- 테스트 코드 영속성 관리 검토 필요
> feat: 유저 탈퇴 기능 추가

- src/main/java/com/backend/connectable/klip/service/KlipService.java
- src/main/java/com/backend/connectable/klip/service/dto/KlipAuthHandleKlaytnAddressResponse.java
- src/main/java/com/backend/connectable/klip/service/dto/KlipAuthHandleResponse.java
- src/main/java/com/backend/connectable/klip/service/dto/KlipAuthLoginResponse.java
- src/main/java/com/backend/connectable/security/SecurityConfiguration.java
- src/main/java/com/backend/connectable/user/domain/UserRepository.java
- src/main/java/com/backend/connectable/user/service/UserService.java
- src/main/java/com/backend/connectable/user/ui/UserController.java
- src/main/java/com/backend/connectable/user/ui/dto/UserLoginRequest.java
- src/main/java/com/backend/connectable/user/ui/dto/UserLoginResponse.java
- src/main/java/com/backend/connectable/user/ui/dto/UserLoginSuccessResponse.java
- src/test/java/com/backend/connectable/user/service/UserServiceTest.java
- src/test/java/com/backend/connectable/user/ui/UserControllerTest.java
- klip으로 로그인 할 수 있도록 백엔드 API 구축
- 추후 메모리 관리를 위한 리팩터링이 진행되었으면 함
> feat: klip 로그인 구현

- build.gradle
- src/main/resources/application.yml
- AWS SSM (ParameterStore) 의존성 추가 
- application.yml Dev 환경 분기 및 DB 설정 추가
- 로컬 환경 구동 시 테스트 불가
> feat: AWS ParameterStore 기능 추가

- build.gradle
- src/main/resources/application.yml
- aws 파라미터 스토어 의존성관리 버전 수정
- Flyway 의존성 삭제처리 됨. ( 추후 추가 필요 )
> fix: aws parameter-store 의존성 버전 수정

- src/main/java/com/backend/connectable/user/domain/User.java
- src/main/java/com/backend/connectable/user/service/UserService.java
- src/main/java/com/backend/connectable/user/ui/UserController.java
- src/main/java/com/backend/connectable/user/ui/dto/UserModifyRequest.java
- src/main/java/com/backend/connectable/user/ui/dto/UserModifyResponse.java
- src/main/resources/application.yml
- src/test/java/com/backend/connectable/user/service/UserServiceTest.java
- 유저 수정 기능 추가
- Query 로깅 인자 확인 가능하게끔 yaml 설정 변경
- Transactional 관리 방법에 대해 리서칭 필요
> feat: 유저 수정 기능 추가

- src/main/java/com/backend/connectable/user/domain/User.java
- src/test/java/com/backend/connectable/user/domain/UserTest.java
- User.hasNickname(), User.hasPhoneNumber()의 NPE를 수정합니다.
> fix: user 도메인 npe 수정

- src/main/java/com/backend/connectable/security/WebConfigure.java
> fix: cors methods 추가

- src/main/java/com/backend/connectable/security/SecurityConfiguration.java
- 스프링 시큐리티 Options 설정 permitAll() 권한 부여
> fix: 스프링 시큐리티 Options 설정

- src/main/java/com/backend/connectable/user/service/UserService.java
- UserService 회원 수정 부분 @Transactional 추가
- 클래스 단위는 read 커넥션으로 잡아두고, write connection은 메소드 단위로 잡아둔 것 추후 검토 필요
- 추후 전반적으로 트랜잭션 관리 정책 정리 필요
> fix: write connection 트랜잭셔널 어노테이션 추가

- src/main/java/com/backend/connectable/event/domain/Event.java
- src/main/java/com/backend/connectable/event/domain/EventRepository.java
- src/main/java/com/backend/connectable/event/domain/EventRepositoryCustom.java
- src/main/java/com/backend/connectable/event/domain/EventRepositoryImpl.java
- src/main/java/com/backend/connectable/event/domain/SalesOption.java
- src/main/java/com/backend/connectable/event/service/EventService.java
- src/main/java/com/backend/connectable/event/ui/EventController.java
- src/main/java/com/backend/connectable/event/ui/dto/EventResponse.java
- src/main/java/com/backend/connectable/security/SecurityConfiguration.java
- src/test/java/com/backend/connectable/event/service/EventServiceTest.java
- src/test/java/com/backend/connectable/event/ui/EventControllerTest.java
- 이벤트 목록 조회 API 개발
- Event 컨트롤러 테스트 WebMvcTest 인증처리 필터 제외처리 됨.
- User 엔티티와 연관관계 매핑되어있지 않음
- artistId 필드 추후 검토 후 Event 엔티티 내 추가 필요
> feat: 이벤트 목록 조회

- src/main/java/com/backend/connectable/user/service/UserService.java
- transactional ReadOnly 속성 삭제
> fix: transactional ReadOnly 속성 삭제

- src/main/java/com/backend/connectable/exception/ConnectableException.java
- src/main/java/com/backend/connectable/exception/ErrorType.java
- src/main/java/com/backend/connectable/exception/ExceptionResponse.java
- src/main/java/com/backend/connectable/exception/GlobalExceptionHandler.java
- RestControllerAdvice 이용하여 Exception Handling 처리
- validation 등 예외처리 케이스 추가 필요
> feat: exception global 처리 추가

- src/main/java/com/backend/connectable/user/service/UserService.java
- Transactional 어노테이션 User 변경 메서드에 도입
> fix: modify user transactional 선언

- src/main/java/com/backend/connectable/DataLoader.java
- src/main/java/com/backend/connectable/artist/domain/Artist.java
- src/main/java/com/backend/connectable/artist/domain/repository/ArtistRepository.java
- src/main/java/com/backend/connectable/event/domain/Event.java
- src/main/java/com/backend/connectable/event/domain/dto/EventDetail.java
- src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryCustom.java
- src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryImpl.java
- src/main/java/com/backend/connectable/event/service/EventService.java
- src/main/java/com/backend/connectable/event/ui/EventController.java
- src/main/java/com/backend/connectable/event/ui/dto/EventDetail.java
- src/main/java/com/backend/connectable/event/ui/dto/EventDetailResponse.java
- src/main/java/com/backend/connectable/security/SecurityConfiguration.java
- src/test/java/com/backend/connectable/event/domain/repository/TicketRepositoryTest.java
- src/test/java/com/backend/connectable/event/service/EventServiceTest.java
- src/test/java/com/backend/connectable/event/ui/EventControllerTest.java
- src/test/java/com/backend/connectable/user/service/UserServiceTest.java
- 이벤트 상세 조회 기능 추가 
- 아티스트 도메인 추가
- Event  Service 레이어 Dto 변환 리팩토링 필요
- 통합 테스트 규격화 필요
- queryDsl 인라인 뷰에 대한 개선방안 리서치
> feat: events detail

- src/main/java/com/backend/connectable/user/service/UserService.java
- src/main/java/com/backend/connectable/user/ui/UserController.java
- src/main/java/com/backend/connectable/user/ui/dto/UserTicketListResponse.java
- src/test/java/com/backend/connectable/user/service/UserServiceTest.java
> fix: 프론트 요구 명세에 따라 status 필드 추가

- src/main/java/com/backend/connectable/DataLoader.java
- src/main/java/com/backend/connectable/event/domain/dto/EventDetail.java
- src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryImpl.java
- src/main/java/com/backend/connectable/event/service/EventService.java
- src/main/java/com/backend/connectable/event/ui/dto/EventDetailResponse.java
- src/main/java/com/backend/connectable/event/ui/dto/EventResponse.java
- src/main/java/com/backend/connectable/event/ui/dto/TicketResponse.java
- src/main/java/com/backend/connectable/global/common/util/DateTimeUtil.java
- src/main/java/com/backend/connectable/user/ui/dto/UserTicketResponse.java
- src/test/java/com/backend/connectable/event/ui/EventControllerTest.java
- LocalDateTime -> Timestamp 유틸 생성
- 더미데이터 추가
- 이벤트 상세 조회 artistImage 필드 추가 
- ticket Metadata 이슈 미해결
> fix: QA 수정사항(타임스탬프 변환, artistImage필드 추가, 더미데이터 추가)

- src/main/java/com/backend/connectable/DataLoader.java
- src/main/java/com/backend/connectable/event/domain/Ticket.java
- src/main/java/com/backend/connectable/event/domain/TicketMetadataConverter.java
- src/main/java/com/backend/connectable/event/domain/dto/EventTicket.java
- src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryImpl.java
- src/main/java/com/backend/connectable/event/ui/dto/TicketResponse.java
- src/test/java/com/backend/connectable/event/service/EventServiceTest.java
- ticket.ticketMetadata null로 내려오던 현상 수정
> fix: 티켓 메타데이터 null로 내려오는 이슈 수정

- src/main/java/com/backend/connectable/DataLoader.java
- src/main/java/com/backend/connectable/event/domain/Ticket.java
- src/main/java/com/backend/connectable/event/domain/TicketMetadataConverter.java
- src/main/java/com/backend/connectable/event/domain/dto/EventTicket.java
- src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryImpl.java
- src/main/java/com/backend/connectable/event/ui/dto/TicketResponse.java
- src/main/java/com/backend/connectable/user/domain/repository/UserRepositoryImpl.java
- src/test/java/com/backend/connectable/event/service/EventServiceTest.java
- /users/ticket 티켓 메타데이터 null로 내려오는 현상 수정
> fix: 유저 소지한 티켓데이터 내 티켓메타데이터 필드 null 현상 수정

- src/main/java/com/backend/connectable/DataLoader.java
- src/main/java/com/backend/connectable/event/service/EventService.java
- src/main/java/com/backend/connectable/event/ui/dto/TicketMetadataResponse.java
- src/main/java/com/backend/connectable/kas/service/KasService.java
- src/main/java/com/backend/connectable/kas/service/dto/dto/ContractDeployRequest.java
- src/main/java/com/backend/connectable/kas/service/dto/dto/TokenRequest.java
- src/main/java/com/backend/connectable/kas/service/dto/dto/TokenSendRequest.java
- src/main/java/com/backend/connectable/kas/service/dto/dto/TransactionOptionFeePayerRequest.java
- src/main/java/com/backend/connectable/kas/service/dto/dto/TransactionOptionRequest.java
> fix: tokenId로 KAS 접근하도록 수정

- src/main/java/com/backend/connectable/exception/GlobalExceptionHandler.java
- src/main/java/com/backend/connectable/exception/MethodArgumentNotValidExceptionResponse.java
- src/main/java/com/backend/connectable/exception/ValidationField.java
- src/main/java/com/backend/connectable/exception/sequence/ValidationGroups.java
- src/main/java/com/backend/connectable/exception/sequence/ValidationSequence.java
- src/main/java/com/backend/connectable/user/ui/UserController.java
- src/main/java/com/backend/connectable/user/ui/dto/UserModifyRequest.java
- 유저 수정시 검증 로직 추가
ㄴ 공란에 대해서 정규식보다 우선순위를 가지고 검증 진행
- 유저 도메인 인수 테스트 추가 시, 예외처리 테스트 케이스 추가 필요
> feat: 유저 수정 request dto 검증 기능

- src/main/java/com/backend/connectable/DataLoader.java
- src/main/java/com/backend/connectable/event/service/EventService.java
- src/main/java/com/backend/connectable/kas/service/KasService.java
- src/main/java/com/backend/connectable/kas/service/dto/ContractDeployRequest.java
- src/main/java/com/backend/connectable/kas/service/dto/ContractDeployResponse.java
- src/main/java/com/backend/connectable/kas/service/dto/ContractItemResponse.java
- src/main/java/com/backend/connectable/kas/service/dto/ContractItemsResponse.java
- src/main/java/com/backend/connectable/kas/service/dto/TokenDeleteRequest.java
- src/main/java/com/backend/connectable/kas/service/dto/TokenHistoriesResponse.java
- src/main/java/com/backend/connectable/kas/service/dto/TokenHistoryResponse.java
- src/main/java/com/backend/connectable/kas/service/dto/TokenRequest.java
- src/main/java/com/backend/connectable/kas/service/dto/TokenResponse.java
- src/main/java/com/backend/connectable/kas/service/dto/TokenSendRequest.java
- src/main/java/com/backend/connectable/kas/service/dto/TokensResponse.java
- src/main/java/com/backend/connectable/kas/service/dto/TransactionOptionFeePayerRequest.java
- src/main/java/com/backend/connectable/kas/service/dto/TransactionOptionRequest.java
- src/main/java/com/backend/connectable/kas/service/dto/TransactionResponse.java
- src/main/java/com/backend/connectable/kas/service/dto/UserFeePayerOptionRequest.java
- src/main/resources/application.yml
- src/test/java/com/backend/connectable/kas/service/KasServiceTest.java
- header에 krn 정보를 담아야하는 것을 수정합니다
- 추가 API (토큰 소각, 토큰 히스토리 조회) 를 구현합니다.
> refactor: KAS API 수정

- src/main/java/com/backend/connectable/security/SecurityConfiguration.java
- src/main/java/com/backend/connectable/user/domain/dto/UserTicket.java
- src/main/java/com/backend/connectable/user/domain/repository/UserRepositoryImpl.java
- src/main/java/com/backend/connectable/user/service/UserService.java
- src/main/java/com/backend/connectable/user/ui/dto/UserTicketResponse.java
- 유저 티켓 목록 아티스트명 누락된 필드 추가
- SecurityConfiguration 유저 티켓 엔드포인트 추가됨
> fix: 유저 아티스트명 필드 누락 수정

- src/main/java/com/backend/connectable/user/domain/repository/UserRepository.java
- src/main/java/com/backend/connectable/user/service/UserService.java
- src/main/java/com/backend/connectable/user/ui/UserController.java
- src/main/java/com/backend/connectable/user/ui/dto/UserValidationResponse.java
- src/test/java/com/backend/connectable/user/domain/UserRepositoryTest.java
- src/test/java/com/backend/connectable/user/service/UserServiceTest.java
- nickname validation 을 도입합니다
- `GET /users/validation?nickname=query`로 질의 가능합니다.
> feat: nickname validation 도입

- src/main/java/com/backend/connectable/DataLoader.java
- src/main/java/com/backend/connectable/event/domain/Event.java
- src/main/java/com/backend/connectable/event/domain/EventSalesOption.java
- src/main/java/com/backend/connectable/event/domain/Ticket.java
- src/main/java/com/backend/connectable/event/domain/TicketSalesStatus.java
- src/main/java/com/backend/connectable/event/domain/dto/EventDetail.java
- src/main/java/com/backend/connectable/event/domain/dto/EventTicket.java
- src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryImpl.java
- src/main/java/com/backend/connectable/event/service/EventService.java
- src/main/java/com/backend/connectable/event/ui/dto/EventDetailResponse.java
- src/main/java/com/backend/connectable/event/ui/dto/TicketResponse.java
- src/main/java/com/backend/connectable/user/domain/dto/UserTicket.java
- src/main/java/com/backend/connectable/user/domain/repository/UserRepositoryImpl.java
- src/main/java/com/backend/connectable/user/ui/dto/UserTicketResponse.java
- src/test/java/com/backend/connectable/event/domain/repository/TicketRepositoryTest.java
- src/test/java/com/backend/connectable/event/ui/EventControllerTest.java
- src/test/java/com/backend/connectable/user/service/UserServiceTest.java
- onSale 필드를 TicketSalesStatus로 변경했습니다!
> refactor: onSale 필드를 TicketSalesStatus로 변경

- src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryCustom.java
- src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryImpl.java
- src/main/java/com/backend/connectable/event/service/EventService.java
- src/main/java/com/backend/connectable/exception/ErrorType.java
- Event 도메인 NPE 발생 현상 확인, Optional로 래핑
- 예외처리 코드 추가
- Q 객체로 ofNullable로 래핑
> refactor: EventRepository NPE 발생이슈 Optional로 리팩토링

- src/main/java/com/backend/connectable/order/service/OrderService.java
- src/main/java/com/backend/connectable/order/ui/dto/OrderResponse.java
- src/test/java/com/backend/connectable/order/service/OrderServiceTest.java
- OrderResponse status 메시지 변경 As-Is : true, To-Be: success
> fix: 주문 상태 등록시 상태 메시지 변경

- src/main/java/com/backend/connectable/DataLoader.java
- src/main/java/com/backend/connectable/order/domain/Order.java
- src/main/java/com/backend/connectable/order/domain/OrderDetail.java
- src/main/java/com/backend/connectable/order/service/OrderService.java
- src/main/java/com/backend/connectable/order/ui/OrderController.java
- src/main/java/com/backend/connectable/security/SecurityConfiguration.java
- src/test/java/com/backend/connectable/event/service/EventServiceTest.java
- src/test/java/com/backend/connectable/order/service/OrderServiceTest.java
1. **Order와 OrderDetail를 단방향 매핑에서 양방향으로 수정했어요.**
- 단방향 매핑의 단점을 발견하여 수정하였습니다. 
- 참고자료 1: https://ocblog.tistory.com/70
- 참고자료 2: https://homoefficio.github.io/2019/04/28/JPA-%EC%9D%BC%EB%8C%80%EB%8B%A4-%EB%8B%A8%EB%B0%A9%ED%96%A5-%EB%A7%A4%ED%95%91-%EC%9E%98%EB%AA%BB-%EC%82%AC%EC%9A%A9%ED%95%98%EB%A9%B4-%EB%B2%8C%EC%96%B4%EC%A7%80%EB%8A%94-%EC%9D%BC/
- 참고자료 3: https://velog.io/@bey1548/OneToMany-%EB%8B%A8%EB%B0%A9%ED%96%A5-%EB%A7%A4%ED%95%91%EC%9D%98-%EB%8B%A8%EC%A0%90
- 연관관계 편의 메서드를 적용했어요.
- 참고자료 1: https://ecsimsw.tistory.com/entry/JPA-%EA%B0%9D%EC%B2%B4%EB%A5%BC-%EA%B3%A0%EB%A0%A4%ED%95%9C-%EC%96%91%EB%B0%A9%ED%96%A5-%EC%97%B0%EA%B4%80-%EC%97%B0%EA%B4%80%EA%B4%80%EA%B3%84-%ED%8E%B8%EC%9D%98-%EB%A9%94%EC%86%8C%EB%93%9C
- 참고자료 2: https://joanne.tistory.com/220
- DirtyCheck로 인해 Ticket이 …
> refactor: order와 orderDetail를 양방향으로 수정

- src/main/java/com/backend/connectable/DataLoader.java
- src/main/java/com/backend/connectable/event/domain/TicketSalesStatus.java
- dataloader 로직 오류 수정
- TicketSalesOption Expired 추가
> fix: dataloader 로직 오류 수정

- src/main/java/com/backend/connectable/event/domain/dto/EventDetail.java
- src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryImpl.java
- src/main/java/com/backend/connectable/event/ui/dto/EventDetailResponse.java
- src/test/java/com/backend/connectable/event/ui/EventControllerTest.java
- eventDetailResponse 에 contractAddress에 대한 응답을 추가합니다. 
- QueryDSL에 조금 추가하고 DTO 조금 추가하니 EventMapper가 뚝딱 알아서 매핑해주네요? 신기합니다...!
- QueryDSL, EventMapper 조금 봐야겠네요 :)
> refactor: contractAddress 추가

- src/main/java/com/backend/connectable/admin/service/AdminService.java
- src/main/java/com/backend/connectable/admin/ui/AdminController.java
- src/main/java/com/backend/connectable/event/domain/Ticket.java
- src/main/java/com/backend/connectable/order/domain/OrderDetail.java
- src/main/java/com/backend/connectable/order/domain/OrderStatus.java
- src/main/java/com/backend/connectable/order/domain/repository/OrderDetailRepository.java
- src/test/java/com/backend/connectable/admin/service/AdminServiceTest.java
- src/test/java/com/backend/connectable/order/domain/OrderDetailTest.java
**1. OrderStatus Enum에 Refund 추가**
- OrderStatus에 주문이 들어왔지만, 선착순에서 밀려 돈을 환불받아야할 요청에 대해 기록할 수 있도록 Refund를 추가하였습니다. 
- OrderDetail의 OrderStatus는 다음과 같은 순서로 변하게 됩니다. 
- REQUESTED
- PAID
- TRANSFER_SUCCESS
- TRANSFER_FAIL
- UNPAID
- REFUND
**2. OrderStatus Enum에서 각 상태 단계 변화 검증 로직 추가**
- REQUESTED일 경우에만 PAID | UNPAID | REFUND 로 변할 수 있게 로직을 부여하였고,
- PAID일 경우에만 TRANSFER_SUCCESS | TRANSFER_FAIL 로 변할 수 있게 로직을 부여합니다. 
- IllegalArgumentException으로 예외처리를 해뒀는데, 저희 예외처리 전략 좀 더 정교하게 수립하여 예외 처리 해둬야할 듯 싶네요. 
**3. API 엔드포인트 구현**
- API 엔드포인트는 다음과 같이 설정하였습니다. 
- PUT /admin/order-details/{id}/paid
- PUT /admin/order-details/{id}/unpaid
- PUT /admin/order-details/{id}/refund
- 수정 요청이라 PUT 방식을 채택했습니다. 
- 좀 더 요청이 명시적이였으면 좋겠다 싶어 url에 행위를 박아두었습니다 (paid, unpaid, refund). 
-  별로면 얘기해주세요 :) 
- 해당 어드민 엔드포인트에 대한 http …
> feat: 어드민을 통한 OrderDetail 상태 변경 기능 구현

- src/main/java/com/backend/connectable/DataLoader.java
- src/main/java/com/backend/connectable/event/domain/repository/TicketRepository.java
- src/main/resources/application.yml
- 현재 저희의 Mock NFT의 설정에 알맞게 dataloader를 재정의하였습니다. 
- 이제 jpa create-drop 그만 씁시다!
> fix: dataloader 설정 재정의

- src/main/java/com/backend/connectable/event/service/EventService.java
- src/main/java/com/backend/connectable/order/domain/repository/OrderRepository.java
- src/main/java/com/backend/connectable/order/domain/repository/OrderRepositoryCustom.java
- src/main/java/com/backend/connectable/order/domain/repository/OrderRepositoryImpl.java
- src/main/java/com/backend/connectable/order/domain/repository/dto/TicketOrderDetail.java
- src/main/java/com/backend/connectable/order/mapper/OrderMapper.java
- src/main/java/com/backend/connectable/order/service/OrderService.java
- src/main/java/com/backend/connectable/order/ui/OrderController.java
- src/main/java/com/backend/connectable/order/ui/dto/OrderDetailResponse.java
- src/main/java/com/backend/connectable/security/SecurityConfiguration.java
- src/main/java/com/backend/connectable/user/service/UserService.java
- src/test/java/com/backend/connectable/order/service/OrderServiceTest.java
- 주문 내역 조회 api
ㄴ 주문에 대한 내역 조회를 도메인으로 보아, OrderRepository 별도 생성하였습니다 :)
- List 조회시 시간 정렬한 경우에 대한 테스트 코드 추가 필요
- DTO 파일명, 함수명등 내부 컨벤션 정의 필요
> feat: 거래 내역 조회 api

- src/test/java/com/backend/connectable/s3/service/S3ServiceTest.java
> fix(S3ServiceTest): 깨지는 테스트 수정

- src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryImpl.java
- 쿼리를 자세히 확인하고, 테스트 코드를 촘촘하게 작성한다.
> fix: totalTicketCount 잘못 내려오는 현상 수정

- src/main/java/com/backend/connectable/order/ui/dto/OrderDetailResponse.java
- src/test/java/com/backend/connectable/order/service/OrderServiceTest.java
- OrderDetailResponse LocalDateTime 응답값 -> timestamp 로 변환
> fix: timestamp 필드 변환 수정

- src/main/java/com/backend/connectable/order/ui/dto/OrderRequest.java
> fix: 주문자명 정규식 검증 제거

- src/main/java/com/backend/connectable/security/JwtAuthenticationFilter.java
- JwtAuthenticationFilter에서 Path와 Token을 로깅합니다
- 디버깅 이후 삭제 예정
> feat: path, token 로깅

- src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryImpl.java
- src/test/java/com/backend/connectable/event/domain/repository/EventRepositoryTest.java
> fix: 티켓 정렬 순서 변경

- build.gradle
- src/main/java/com/backend/connectable/order/ui/OrderController.java
- src/main/resources/application.yml
- src/main/resources/logback-spring.xml
> feat: 주문 신청시 request 로그 슬랙알림

- src/main/java/com/backend/connectable/user/service/UserService.java
- src/main/java/com/backend/connectable/user/ui/UserController.java
- src/main/java/com/backend/connectable/user/ui/dto/UserResponse.java
> fix: get user 로직 수정

- src/main/java/com/backend/connectable/order/domain/repository/OrderRepositoryImpl.java
- src/main/java/com/backend/connectable/order/domain/repository/dto/TicketOrderDetail.java
- src/main/java/com/backend/connectable/order/ui/dto/OrderDetailResponse.java
- src/test/java/com/backend/connectable/order/service/OrderServiceTest.java
- 주문 내역 API 내 하기 필드 추가
1. 이벤트 ID
2. 각 티켓별 가격
> feat: 주문 상세 내역 필드 추가

- src/main/java/com/backend/connectable/user/service/UserService.java
> refactor: 유저 변경 트랜잭션 전파 설정 변경

- build.gradle
- src/main/java/com/backend/connectable/user/ui/UserController.java
- src/main/java/com/backend/connectable/user/ui/dto/UserResponse.java
- src/test/java/com/backend/connectable/acceptance/UserAcceptanceTest.java
- 유저 인수테스트 추가 
> 관련 레퍼런스 [여기](https://www.notion.so/E2E-Test-b3ff3dffcaac43a58b4276c289f58f88)에 정리해두었습니다 !
1. 좋은 인수테스트 구조가 어떤것인지.. 어느 선까지 인수테스트를 작성해야하는지.. 
2. 빌드 타임에서 속도 개선방법 ( DirtiesContext 가 속도에 영향을 끼치는듯 합니다. ) 
등... 고민을 지속하다 우선 리뷰 후에 개선하는 것이 좋을 것 같다 생각하여, PR올립니다.
- 현재 Spring Security 및 더티 체킹 관련하여 테스트코드의 부재로 우선하여 유저 등록 및 수정 테스트 작성하였습니다. 
+) 이슈가 있을 것 같아 local 환경에서 구동되도록 하였습니다.
> feat: 유저 인수테스트 추가

- src/main/java/com/backend/connectable/global/config/swagger/SwaggerConfig.java
- src/main/java/com/backend/connectable/global/config/swagger/Workaround.java
- https://velog.io/@yulhee741/Swagger-servers-url-%EC%B6%94%EA%B0%80%ED%95%98%EA%B8%B0-https-%EC%B6%94%EA%B0%80
- Swagger....
> fix: swagger uri 설정

- src/main/resources/application.yml
> feat: prod 환경 yaml 설정

- Dockerfile
- Jenkinsfile
- docker 이미지 빌드를 위한 Dockerfile 작성
- CI/CD를 위한 Jenkinsfile 작성
> feat: 인프라 관련 file 추가

- build.gradle
- 빌드시 plain jar 파일을 생성하지 않도록 합니다.
> build: plain jar 파일 삭제

- Jenkinsfile
- ecs deploy region 명시 및 기존 region 변경
- 참고 : https://docs.aws.amazon.com/cli/latest/reference/ecs/update-service.html
> fix: region 명시

- Jenkinsfile
- ecr login only supported us-east-1 에 따라 변경
> fix: region 변경

- Jenkinsfile
- task 강제 업데이트 되도록 쉘 수정
* task업데이트 스크립트를 통해 강제되도록 변경
> fix: task 강제 업데이트 되도록 수정

- Jenkinsfile
- if-else 문을 써서 브랜치 분기처리 진행합니다. 
- when을 쓰라는 의견도 많았지만, 이렇게 한번 진행해봅시다!
> fix: Jenkinsfile 브랜치별 분기 처리

- Jenkinsfile
> fix: Jenkinsfile 문법 수정

- src/main/resources/application.yml
> fix: prod환경 log path 수정

- src/main/java/com/backend/connectable/auth/service/AuthService.java
> chore: 인증 메시지 문구 수정

- src/main/java/com/backend/connectable/admin/service/AdminService.java
- src/main/java/com/backend/connectable/admin/ui/AdminController.java
- src/main/java/com/backend/connectable/admin/ui/dto/EventDeploymentRequest.java
- src/main/java/com/backend/connectable/admin/ui/dto/TokenMintingRequest.java
- src/main/java/com/backend/connectable/event/domain/repository/EventRepository.java
- src/main/java/com/backend/connectable/exception/ErrorType.java
- src/test/java/com/backend/connectable/event/domain/repository/EventRepositoryTest.java
- 백엔드에서 nft 발행할 수 있는 기능을 작성합니다.
> feat: 컨트랙트 발행 및 토큰 민팅 기능 구현

- src/main/java/com/backend/connectable/admin/service/AdminService.java
- src/main/java/com/backend/connectable/admin/ui/dto/TokenMintingRequest.java
> fix: 컨트랙트 배포 로직 수정

- src/main/java/com/backend/connectable/DataLoader.java
- src/main/java/com/backend/connectable/admin/service/AdminService.java
- src/main/java/com/backend/connectable/event/domain/Event.java
- src/main/java/com/backend/connectable/event/domain/SalesOption.java
- src/main/java/com/backend/connectable/event/domain/dto/EventDetail.java
- src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryImpl.java
- src/main/java/com/backend/connectable/event/ui/dto/EventDetailResponse.java
- src/test/java/com/backend/connectable/admin/service/AdminServiceTest.java
- src/test/java/com/backend/connectable/event/domain/repository/EventRepositoryTest.java
- src/test/java/com/backend/connectable/event/domain/repository/TicketRepositoryTest.java
- src/test/java/com/backend/connectable/event/ui/EventControllerTest.java
- src/test/java/com/backend/connectable/order/service/OrderServiceTest.java
- src/test/java/com/backend/connectable/user/service/UserServiceTest.java
> fix: eventSalesOption -> salesOption

- src/main/resources/db/migration/V6__alter_event_sales_option_column_name.sql
> fix: event 테이블 필드명 변경

- src/main/java/com/backend/connectable/event/domain/repository/TicketRepositoryCustom.java
- src/main/java/com/backend/connectable/event/service/EventService.java
- src/main/java/com/backend/connectable/kas/service/dto/TokenIdentifier.java
- src/main/java/com/backend/connectable/kas/service/dto/TokensResponse.java
- src/main/java/com/backend/connectable/user/service/UserTicketService.java
- 이벤트 입장시 유저 정보 로그 기록
- 안쓰는 패키지 import 제거
> feature: 이벤트입장 로그 기록

- src/main/resources/db/migration/V7__insert_letslock_artist.sql
> feat: new artist for letslock

- src/main/resources/db/migration/V8__update_artist_data.sql
> fix: 아티스트명, 이미지 변경

- src/main/java/com/backend/connectable/event/service/EventService.java
> fix: 이벤트 노출 순서 변경

- src/main/java/com/backend/connectable/event/domain/repository/TicketRepositoryCustom.java
- src/main/resources/db/migration/V10__update_artist_image_url.sql
- src/main/resources/db/migration/V9__update_connectable_artist_name.sql
> fix: artistname 변경

- src/main/java/com/backend/connectable/auth/ui/AuthController.java
- src/main/java/com/backend/connectable/user/ui/UserController.java
- HandlerMethodArgumentResolverComposite 이슈 발생하여 fix합니다.
> fix: HandlerMethodArgumentResolverComposite이슈 수정

- src/test/java/com/backend/connectable/artist/domain/ArtistTest.java
- src/test/java/com/backend/connectable/artist/domain/repository/ArtistRepositoryTest.java
1. **아티스트 도메인 테스트 작성**
- 별거 없어서 생성로직, getter 검증했습니다,,,
2. **레포지토리 테스트**
- 그냥 기본적으로 JPA가 제공해주는 메서드 가지고 어떻게 동작했는지 테스트해봤습니다~
> test: artist 패키지 테스트 작성

- src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryImpl.java
- src/main/java/com/backend/connectable/kas/service/contract/KasContractService.java
- src/test/java/com/backend/connectable/acceptance/AuthAcceptanceTest.java
- src/test/java/com/backend/connectable/auth/service/AuthServiceTest.java
- src/test/java/com/backend/connectable/auth/ui/AuthControllerTest.java
- src/test/java/com/backend/connectable/event/service/EventServiceTest.java
- src/test/java/com/backend/connectable/event/ui/EventControllerTest.java
- src/test/java/com/backend/connectable/kas/service/KasServiceTest.java
- Event 패키지 테스트 코드 작성 진행. 
- event 도메인의 end-point에 대한 테스트 수트는 충분하다 판단하였습니다. 
- Service 레이어에 테스트 코드가 부족하여, 서비스 코드 테스트 작성을 진행하였습니다. 
- 테스트 진행중에 exception이 터지는 부분이 있는데, 이부분은 정합성이 고려되었을 때는 발생하지 않을 이슈이긴 해서 ToDo로 논의해보면 좋겠다 싶어 기재해놓았습니다. 
- 저는 Production 코드에 ToDo가 늘어나는 것이 이슈가 되진 않는다 생각하여 ToDo를 넣었는데, 관련해서 의견 부탁드립니다. 
- KasService를 호출하는 부분에서 테스트시 에러 발생하여 findTicketByUserAddress, getTicketInfo 두 메소드에 대한 테스트에 애를 먹다가 일단 패스했습니다. 
- 단위 테스트이기에, 외부 모듈에 대한 의존성이 없도록 하여 크게 잡아도 중간 크기의 테스트 ( DB I/O 등을 최대로 사용하되, 서드 파티에 대해서는 테스트에 포함되지 않는 ) 였으면 하는데,, 비즈니스 로직에 써드파티가 포함되어야하는 것이 맞긴하니 어디까지 테스트 해야하는지, 어떻게 테스트 해야하는지조차 감이 잘 오진 않네요 ^^; 아낌없는 조언 부탁드립니다. 
.. 여러 고민이 켜켜이 쌓인 와중에 좋은 테스트가 뭘까 객체지향적인 코드는 뭘까 ! 고민하며 부족함을 느끼고.. 공부하고.. 코드를 지우고 싸이클이 반복되며 힘든 한주를 보낸것 같은데요 ㅎㅎ 와중에 [이 …
> test: EventService 테스트

- README.md
- readme 작성
- 저희의 Readme가 필요할 듯 하여 하기와 같이 작성하였습니다.
- Diagram 코드는 하기와 같습니다.
```
from diagrams import Cluster, Diagram
from diagrams.aws.compute import EC2
from diagrams.aws.storage import S3
from diagrams.aws.management import ParameterStore
from diagrams.aws.database import RDS
from diagrams.aws.network import ALB
from diagrams.aws.network import Route53
with Diagram("Connectable", show=False):
dns = Route53("dns")
alb = ALB("Application_Load_Balancer")
with Cluster("Service"):
svc_group = [EC2("worker1"),
EC2("worker2"),
EC2("worker3")]
svc_group - S3('storage')
svc_group - ParameterStore('ssm')
with Cluster("DB Cluster"):
db_main = RDS("connectable_db")
db_main - [RDS("connectable_replication")]
dns >> alb >> svc_group >> db_main
```
- Tech Spec에 특정된 버전 중 상이한 것이 있다면 피드백 부탁드립니다.
- AWS …
> docs(Readme): 문서 초안 작성

- src/main/java/com/backend/connectable/artist/domain/Comment.java
- src/main/java/com/backend/connectable/artist/domain/dto/ArtistComment.java
- src/main/java/com/backend/connectable/artist/domain/repository/CommentRepository.java
- src/main/java/com/backend/connectable/artist/domain/repository/CommentRepositoryCustom.java
- src/main/java/com/backend/connectable/artist/domain/repository/CommentRepositoryImpl.java
- src/main/java/com/backend/connectable/artist/service/ArtistService.java
- src/main/java/com/backend/connectable/artist/ui/ArtistController.java
- src/main/java/com/backend/connectable/artist/ui/dto/ArtistCommentRequest.java
- src/main/java/com/backend/connectable/artist/ui/dto/ArtistCommentResponse.java
- src/main/java/com/backend/connectable/artist/ui/dto/ArtistDetailResponse.java
- src/main/java/com/backend/connectable/exception/ErrorType.java
- src/main/java/com/backend/connectable/security/config/SecurityConfiguration.java
- src/main/resources/db/migration/V11__create_artist_comment_table.sql
- src/test/java/com/backend/connectable/artist/service/ArtistServiceTest.java
- src/test/java/com/backend/connectable/artist/ui/ArtistControllerTest.java
- src/test/java/com/backend/connectable/fixture/ArtistFixture.java
- 아티스트 페이지 방문 유저에 대한 방문록 기능 추가
> feat: artist페이지 방명록 기능

- README.md
- Tech Spec 추가된 것들 README에 업데이트
- 없습니당
> docs: tech spec 업데이트

- src/main/java/com/backend/connectable/artist/ui/dto/ArtistDetailResponse.java
- src/test/java/com/backend/connectable/artist/ui/ArtistControllerTest.java
> fix(ArtistDetailResponse): 머지 과정에서 삭제된 부분 회생

- src/main/java/com/backend/connectable/artist/ui/dto/ArtistCommentResponse.java
- src/test/java/com/backend/connectable/artist/service/ArtistServiceTest.java
- writtenAt datetime string -> Long(epoch time) 으로 변경
> fix: writtenAt 타임 스탬프로 변경

- src/main/java/com/backend/connectable/artist/domain/dto/ArtistDetail.java
- src/main/java/com/backend/connectable/artist/domain/repository/ArtistRepositoryImpl.java
- src/main/java/com/backend/connectable/artist/service/ArtistService.java
- 아티스트 상세 조회 id 누락 수정
- 메소드 Transactional 어노테이션 추가
> fix: 트랜잭셔널 어노테이션 추가 및 아티스트 상세 조회시 id누락부

- src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryImpl.java
- src/test/java/com/backend/connectable/event/domain/repository/EventRepositoryTest.java
- 아티스트별 이벤트를 가져오는 쿼리 수정 합니다!
- 테스트 코드를 정성껏 씁시다...! 커버리지를 높이기 위한 테스트는 무의미하다...! 많이 배워갑니다 🙏
> fix: 아티스트별 이벤트 쿼리 수정

- src/main/java/com/backend/connectable/event/domain/dto/EventDetail.java
- src/main/java/com/backend/connectable/event/domain/repository/EventRepositoryImpl.java
- src/main/java/com/backend/connectable/event/ui/dto/EventDetailResponse.java
- src/test/java/com/backend/connectable/event/service/EventServiceTest.java
- src/test/java/com/backend/connectable/event/ui/EventControllerTest.java
- EventDetail에 artistId 정보 추가합니다!
> refactor: EventDetail에 artistId 정보 추가

- README.md
> docs: ERD 업데이트

- src/main/java/com/backend/connectable/artist/service/ArtistService.java
- src/main/java/com/backend/connectable/event/domain/repository/TicketRepositoryCustom.java
- src/main/java/com/backend/connectable/event/domain/repository/TicketRepositoryImpl.java
- src/main/java/com/backend/connectable/exception/ErrorType.java
- src/main/java/com/backend/connectable/order/service/OrderService.java
- src/main/java/com/backend/connectable/order/ui/dto/OrderRequest.java
- src/test/java/com/backend/connectable/order/service/OrderServiceTest.java
1. **일괄 구매 수량 옵션 추가 구현합니다**
- Test 픽스쳐로 조금 바꿨고
- 로직 명시적으로 메서드 분리해서 구현해봤어요~
> refactor: 일괄 구매 수량 옵션 추가
